### ISSUE TITLE
Убрать секунды из отображения всплывающих подписей значений на графиках

### ISSUE THREAD

**Issue by shaperman** [ut8ia/yii2-ecoclient#3]
Убрать секунды из отображения всплывающих подписей значений на графиках. Всплывающая подпись на графике - дата, время, значение (то есть как и сейчас, но без секунд).

**Comment by ut8ia** [comment]
реализовано с возможностью конфига формата для случаев даты и даты - времени : 
   public $dateFormat = 'd.m.Y';
   public $dateTimeFormat = 'd.m.Y H:i';
