### ISSUE TITLE
Линия на графике "Безопасный для здровья уровень"

### ISSUE THREAD

**Issue by shaperman** [ut8ia/yii2-ecoclient#5]
На графике количества пыли в воздухе провести прямую с подписью "безопасный для здровья уровень".

**Comment by ut8ia** [comment]
added like static line : 
'datasets' => [
                    [
                        'label' => "Max average level",
                        'backgroundColor' => "rgba(132,255,199,0.2)",
                        'borderColor' => "rgba(132,255,199,1)",
                        'pointBackgroundColor' => "rgba(132,255,199,1)",
                        'pointBorderColor' => "#fff",
                        'pointHoverBackgroundColor' => "#fff",
                        'pointHoverBorderColor' => "rgba(132,255,199,1)",
                        'data' => array_fill(0,count($labels),Ecoclient::MAX_AVERAGE_YEAR_DUST_LEVEL)
                    ],
